title:   Hadier Besheer
logo: "/images/image.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
 name is Hadier, Recent graduate of Business intelligence (BI) , Bachelor degree in Business and Project Management Certified (PMC) from PMI . I am passionate about diving in data, and building business logics when communicating business and tech teams.

However, it was a big Challenge as Operational Manager  turned to Data Analyst , Coding and manipulating date helping me to improve my analytical mindset and come up with  business solution and implement new strategic. 

I love organizing and manipulating a pool of numbers and data , into a meaningful BI dashboard. I also love develop and analyze current business processes, in order to achieve higher operation efficiency.
  <br><br><br>
  <a href="https://www.linkedin.com/in/hadier-ahmed-693b78277/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://https://github.com/hadierbasheer/portfolios.git#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/hadierbesheer/Portfolio-Hadier-Ahmed-1ff0d38d8a5446d1a2c4e44363bb3581">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal             
 
